# txt 수정하기

In [2]:
import os
import pandas as pd

In [3]:
path = '../data__/train_annotation.txt'

df = pd.read_csv(path, header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,./data__/train/5820554de4b0ced31a7fd174.jpg 129,78,178,127,1,233,77,283,126,2,...,176,384,206,413,5,210,383,241,414,6
1,./data__/train/58205570e4b0bb347e7dec70.jpg 142,104,188,149,1,225,101,270,146,2,...,179,390,207,416,5,209,391,236,416,6
2,./data__/train/582055c0e4b0ced31a7fd17e.jpg 131,65,179,114,1,222,66,268,111,2,...,170,373,199,402,5,202,373,229,400,6
3,./data__/train/582055fbe4b0ced31a7fd180.jpg 146,72,189,115,1,239,69,285,115,2,...,183,378,210,405,5,217,376,243,403,6
4,./data__/train/58205636e4b0ced31a7fd182.jpg 138,67,188,117,1,231,66,279,114,2,...,183,387,211,414,5,214,388,241,415,6

In [4]:
new_f = open('../data__/train_annotation__.txt', mode='w')

with open('../data__/train_annotation.txt', mode='r') as f:
    data = f.readlines()
    
    for i in range(len(data)):
        data_lst = data[i].split(',')
        title = data_lst[0]
        title_ = title.replace('data__', 'data')        
        val = title_.split(' ')
        data_lst = val + data_lst[1:]
        res = ''
        for j in range(len(data_lst)):
            res += data_lst[j]
            if j % 5 == 0:
                res += ' '
            else:
                res += ','
                    
        new_f.write(res[:-1])
    
new_f.close()

In [5]:
new_f = open('../data__/test_annotation__.txt', mode='w')

with open('../data__/test_annotation.txt', mode='r') as f:
    data = f.readlines()
    
    for i in range(len(data)):
        data_lst = data[i].split(',')
        title = data_lst[0]
        title_ = title.replace('data__', 'data')        
        val = title_.split(' ')
        data_lst = val + data_lst[1:]
        res = ''
        for j in range(len(data_lst)):
            res += data_lst[j]
            if j % 5 == 0:
                res += ' '
            else:
                res += ','
                    
        new_f.write(res[:-1])
    
new_f.close()

In [41]:
new_f = open('../data/val_annotation__.txt', mode='w')

with open('../data/val_annotation.txt', mode='r') as f:
    data = f.readlines()
    
    for i in range(len(data)):
        data_lst = data[i].split(',')
        title = data_lst[0]
        title_ = title.replace('data__', 'data')        
        val = title_.split(' ')
        data_lst = val + data_lst[1:]
        res = ''
        for j in range(len(data_lst)):
            res += data_lst[j]
            if j % 5 == 0:
                res += ' '
            else:
                res += ','
                    
        new_f.write(res[:-1])
    
new_f.close()